### ISSUE TITLE
kconfig 配置值有无效值

### ISSUE THREAD

**Issue by SummerGift** [qiyongzhong0/crclib#1]
作者你好，我发现 kconfig 的配置值似乎有错误，可参考这个 [issue](https://github.com/RT-Thread/env/issues/132)

![image](https://user-images.githubusercontent.com/22132180/95667093-b5047b80-0b93-11eb-8e62-ba21889204b5.png)

**Comment by qiyongzhong0** [comment]
应该是Ubuntu不支持hex类型的缘故。CRCxx_POLY使用的是hex类型，如果改成int类型，在配置选项时会很不方便，生成的多项式宏可读性差，所以不建议修改。@SummerLife

**Comment by dongly** [comment]
windows 下也有一样的报警，你的窗口调小一点就可以看见报警，我有点怀疑是env的问题
```
E:\Project\tools\env\tools\ConEmu\ConEmu\..\..\..\packages/packages/iot/pdulib/Kconfig:4:warning: leading whitespace ignored
E:\Project\tools\env\tools\ConEmu\ConEmu\..\..\..\packages/packages/misc/crclib/Kconfig:46:warning: 'CRC8_POLY': number is invalid
E:\Project\tools\env\tools\ConEmu\ConEmu\..\..\..\packages/packages/misc/crclib/Kconfig:81:warning: 'CRC16_POLY': number is invalid
E:Your display is too small to run Menuconfig!\..\packages/packages/misc/crclib/Kconfig:116:warning: 'CRC32_POLY': number is invalid
```
https://github.com/RT-Thread/env/issues/132#issuecomment-706572634

**Comment by SummerGift** [comment]
> windows 下也有一样的报警，你的窗口调小一点就可以看见报警，我有点怀疑是env的问题
> 
> ```
> E:\Project\tools\env\tools\ConEmu\ConEmu\..\..\..\packages/packages/iot/pdulib/Kconfig:4:warning: leading whitespace ignored
> E:\Project\tools\env\tools\ConEmu\ConEmu\..\..\..\packages/packages/misc/crclib/Kconfig:46:warning: 'CRC8_POLY': number is invalid
> E:\Project\tools\env\tools\ConEmu\ConEmu\..\..\..\packages/packages/misc/crclib/Kconfig:81:warning: 'CRC16_POLY': number is invalid
> E:Your display is too small to run Menuconfig!\..\packages/packages/misc/crclib/Kconfig:116:warning: 'CRC32_POLY': number is invalid
> ```
> 
> [RT-Thread/env#132 (comment)](https://github.com/RT-Thread/env/issues/132#issuecomment-706572634)

如果是这样的话，就说明 kconfig 前端软件认为这个 kconfig 语法有问题。
